name: my_project_name
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  mockito: ^5.4.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: '>=3.0.0 <5.0.0'
  lints: ^2.0.0
  test: ^1.21.0
